# Generated by Django 5.1.4 on 2024-12-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='updatet',
            new_name='updated',
        ),
    ]
